"""payment-related-tables

Revision ID: 05c441faf1f7
Revises: 4ae62a98ccef
Create Date: 2026-08-11 10:49:25.895624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import app.db.models.shared


# revision identifiers, used by Alembic.
revision: str = '05c441faf1f7'
down_revision: Union[str, Sequence[str], None] = '4ae62a98ccef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reader_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stripe_payment_intent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_invoice_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'REFUNDED', name='paymentstatus', native_enum=False), nullable=True),
    sa.Column('created_at', app.db.models.shared.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reader_id'], ['readers.id'], name=op.f('fk_payments_reader_id_readers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('stripe_invoice_id', name=op.f('uq_payments_stripe_invoice_id')),
    sa.UniqueConstraint('stripe_payment_intent_id', name=op.f('uq_payments_stripe_payment_intent_id'))
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reader_id', sa.Integer(), nullable=False),
    sa.Column('stripe_subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stripe_price_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELED', 'INCOMPLETE', 'INCOMPLETE_EXPIRED', 'PAST_DUE', 'PAUSED', 'TRIALING', 'UNPAID', name='subscriptionstatus', native_enum=False), nullable=True),
    sa.Column('current_period_start', app.db.models.shared.UTCDateTime(), nullable=False),
    sa.Column('current_period_end', app.db.models.shared.UTCDateTime(), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.models.shared.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.models.shared.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reader_id'], ['readers.id'], name=op.f('fk_subscriptions_reader_id_readers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('stripe_subscription_id', name=op.f('uq_subscriptions_stripe_subscription_id'))
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_articles_slug'), ['slug'])

    with op.batch_alter_table('entitlement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.Enum('PURCHASE', name='entitlementsource', native_enum=False), nullable=True))
        batch_op.add_column(sa.Column('payment_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('granted_at', app.db.models.shared.UTCDateTime(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_entitlement_payment_id_payments'), 'payments', ['payment_id'], ['id'])
        batch_op.drop_column('purchased_at')
        batch_op.drop_column('price_paid')

    with op.batch_alter_table('readers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_readers_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_readers_stripe_customer_id'), ['stripe_customer_id'])
        batch_op.drop_column('is_subscriber')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('readers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_subscriber', sa.BOOLEAN(), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_readers_stripe_customer_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_readers_email'), type_='unique')
        batch_op.drop_column('stripe_customer_id')

    with op.batch_alter_table('entitlement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_paid', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('purchased_at', sa.DATETIME(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_entitlement_payment_id_payments'), type_='foreignkey')
        batch_op.drop_column('granted_at')
        batch_op.drop_column('payment_id')
        batch_op.drop_column('source')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_articles_slug'), type_='unique')

    op.drop_table('subscriptions')
    op.drop_table('payments')
    # ### end Alembic commands ###
