"""notifications-table

Revision ID: 11d56edb7700
Revises: 05c441faf1f7
Create Date: 2026-08-13 16:52:07.316573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import app.db.models.shared


# revision identifiers, used by Alembic.
revision: str = '11d56edb7700'
down_revision: Union[str, Sequence[str], None] = '05c441faf1f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('reader_id', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.models.shared.UTCDateTime(), nullable=True),
    sa.Column('sent_at', app.db.models.shared.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_notifications_article_id_articles')),
    sa.ForeignKeyConstraint(['reader_id'], ['readers.id'], name=op.f('fk_notifications_reader_id_readers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('article_id', 'reader_id', name=op.f('uq_notifications_article_id_reader_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
