"""oauth_accounts_table

Revision ID: 46b8dbad819a
Revises: 11d56edb7700
Create Date: 2026-08-14 14:06:29.677265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import app.db.models.shared


# revision identifiers, used by Alembic.
revision: str = '46b8dbad819a'
down_revision: Union[str, Sequence[str], None] = '11d56edb7700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reader_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE', name='oauthprovider', native_enum=False), nullable=False),
    sa.Column('provider_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', app.db.models.shared.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reader_id'], ['readers.id'], name=op.f('fk_oauth_accounts_reader_id_readers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_accounts')),
    sa.UniqueConstraint('provider', 'provider_account_id', name=op.f('uq_oauth_accounts_provider_provider_account_id')),
    sa.UniqueConstraint('reader_id', 'provider', name=op.f('uq_oauth_accounts_reader_id_provider'))
    )
    with op.batch_alter_table('entitlement', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_reader_article'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_entitlement_reader_id_article_id'), ['reader_id', 'article_id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=18),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=18),
               nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('entitlement', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_entitlement_reader_id_article_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_reader_article'), ['reader_id', 'article_id'])
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)

    op.drop_table('oauth_accounts')
    # ### end Alembic commands ###
