"""remove_column_and_index

Revision ID: 4ae62a98ccef
Revises: e65c0b884d56
Create Date: 2026-08-03 10:30:53.870890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import app.db.models.shared


# revision identifiers, used by Alembic.
revision: str = '4ae62a98ccef'
down_revision: Union[str, Sequence[str], None] = 'e65c0b884d56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_is_published'))
        batch_op.drop_column('email_sent')

    with op.batch_alter_table('readers', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('readers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_sent', sa.BOOLEAN(), nullable=False))
        batch_op.create_index(batch_op.f('ix_articles_is_published'), ['is_published'], unique=False)

    # ### end Alembic commands ###
