"""no-article-deletions

Revision ID: 74463e67a573
Revises: 313ed31d7fdd
Create Date: 2026-04-20 11:55:03.277508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import app.db.models.shared


# revision identifiers, used by Alembic.
revision: str = '74463e67a573'
down_revision: Union[str, Sequence[str], None] = '313ed31d7fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deleted_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deleted_articles_slug'))

    op.drop_table('deleted_articles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted_articles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('slug', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deleted_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deleted_articles_slug'), ['slug'], unique=False)

    # ### end Alembic commands ###
