"""article-purchases

Revision ID: e65c0b884d56
Revises: 74463e67a573
Create Date: 2026-04-20 16:39:57.483822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import app.db.models.shared


# revision identifiers, used by Alembic.
revision: str = 'e65c0b884d56'
down_revision: Union[str, Sequence[str], None] = '74463e67a573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entitlement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reader_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('price_paid', sa.Integer(), nullable=False),
    sa.Column('purchased_at', app.db.models.shared.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['reader_id'], ['readers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reader_id', 'article_id', name='uq_reader_article')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entitlement')
    # ### end Alembic commands ###
